services:
  otel-lgtm:
    image: grafana/otel-lgtm:latest
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - 8080:3000 # grafana
      - 4317:4317 # OpenTelemetry GRPC endpoint
      - 4318:4318 # OpenTelemetry HTTP endpoint
      # - name: grafana
      #   port: 3000
      # - name: otel-grpc
      #   port: 4317
      # - name: otel-http
      #   port: 4318
    volumes:
      - ./grafana/dashboards:/dashboards
      - ./grafana/provisioning:/otel-lgtm/grafana/conf/provisioning
    env_file:
      - ./grafana/config.monitoring
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health" ]
    #   start_period: 30s
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

networks:
  monitoring:
    driver: bridge
