$schema: 'https://moonrepo.dev/schemas/project.json'

stack: 'infrastructure'
layer: 'configuration'

tasks:
  watch:
    description: 'Docker compose up'
    command: 'docker-compose up'
    options:
      runInCI: false

  start:
    description: 'Docker compose up detached'
    command: 'docker-compose up -d'
    options:
      runInCI: false

  stop:
    description: 'Docker compose down'
    command: 'docker-compose down'
    options:
      runInCI: false
