query GetImportJobItemPromotionEligibility($input: ImportJobItemPromotionEligibilityInput!) {
  importJobItemPromotionEligibility(input: $input) {
    importJobItemId
    isEligible
    unresolvedRequiredFields
  }
}
