mutation RefreshImportDiscovery($input: RefreshImportDiscoveryInput!) {
  refreshImportDiscovery(input: $input) {
    newSourceItemRefs
    removedSourceItemRefs
    discovery {
      id
      dataSource
      sourceRef
      label
      tracks {
        id
        sourceItemRef
        label
        position
        isSelected
      }
    }
  }
}
