version: '3.9'

services:
  database:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
