version: '3.9'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - UI_URL
      - MEDIA_URL
      - PORT
      - POSTGRES_HOST=database
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - AUTH0_ISSUER_URL
      - AUTH0_AUDIENCE
    ports:
      - ${PORT}:${PORT}
    networks:
      - db-network
      - local-network
    volumes:
      - media-volume:/app/media
      - stream-volume:/app/stream
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    networks:
      - db-network
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  stream-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./stream
  media-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./media

networks:
  db-network:
    driver: bridge
    internal: true
  local-network:
