CREATE TABLE "music"."AlbumImage" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "album_id" UUID NOT NULL,
  "resolution" VARCHAR(255) NOT NULL,
  "url" VARCHAR(255) NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "FK_AlbumImage_Album" FOREIGN KEY ("album_id") REFERENCES "music"."Album" ("id")
);
