/* eslint-disable -- generated by GraphQL Code Generator */

import { gql } from '@urql/core';
import { Injectable } from '@angular/core';
import type { TypedDocumentNode } from '@urql/core';
import { GraphqlQuery, GraphqlMutation } from '@/core/services/graphql-operations';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format. */
  DateTime: { input: any; output: any; }
};

export type ArtistsInput = {
  pagination?: InputMaybe<PagePaginationInput>;
};

export type Artwork = {
  __typename?: 'Artwork';
  /** The dominant color of the artwork */
  dominantColor: Scalars['String']['output'];
  /** The template URL with {size} placeholder; use preset names (small, medium, large) */
  url: Scalars['String']['output'];
};

export type BackstageArtist = {
  __typename?: 'BackstageArtist';
  artwork?: Maybe<Artwork>;
  createdAt: Scalars['DateTime']['output'];
  createdBy: Scalars['String']['output'];
  genres?: Maybe<Array<BackstageGenre>>;
  id: Scalars['ID']['output'];
  mediaStatus?: Maybe<Scalars['String']['output']>;
  name: Scalars['String']['output'];
  status: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
  updatedBy: Scalars['String']['output'];
  verified: Scalars['Boolean']['output'];
};

export type BackstageGenre = {
  __typename?: 'BackstageGenre';
  createdAt: Scalars['DateTime']['output'];
  createdBy: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  status: Scalars['String']['output'];
  updatedAt: Scalars['DateTime']['output'];
  updatedBy: Scalars['String']['output'];
};

export type CreateArtistInput = {
  genres: Array<Scalars['String']['input']>;
  name: Scalars['String']['input'];
  verified: Scalars['Boolean']['input'];
};

export type CreateGenreInput = {
  name: Scalars['String']['input'];
  slug: Scalars['String']['input'];
};

export type GenresFiltersInput = {
  /** The IDs of the genres */
  ids?: InputMaybe<Array<Scalars['String']['input']>>;
  /** The search query */
  search?: InputMaybe<Scalars['String']['input']>;
};

export type GenresInput = {
  filters?: InputMaybe<GenresFiltersInput>;
  pagination?: InputMaybe<PagePaginationInput>;
};

export type Mutation = {
  __typename?: 'Mutation';
  createArtist: BackstageArtist;
  createGenre: BackstageGenre;
  generateArtistArtworkUploadToken: UploadToken;
  updateArtist: BackstageArtist;
  updateGenre: BackstageGenre;
};


export type MutationCreateArtistArgs = {
  artist: CreateArtistInput;
};


export type MutationCreateGenreArgs = {
  genre: CreateGenreInput;
};


export type MutationGenerateArtistArtworkUploadTokenArgs = {
  id: Scalars['String']['input'];
};


export type MutationUpdateArtistArgs = {
  artist: UpdateArtistInput;
  id: Scalars['String']['input'];
};


export type MutationUpdateGenreArgs = {
  genre: UpdateGenreInput;
  id: Scalars['String']['input'];
};

export type PagePaginationInput = {
  /** The limit of the page */
  limit?: InputMaybe<Scalars['Int']['input']>;
  /** The offset of the page */
  offset?: InputMaybe<Scalars['Int']['input']>;
};

export type Query = {
  __typename?: 'Query';
  backstageArtist: BackstageArtist;
  backstageArtists: Array<BackstageArtist>;
  backstageGenre: BackstageGenre;
  backstageGenres: Array<BackstageGenre>;
};


export type QueryBackstageArtistArgs = {
  id: Scalars['String']['input'];
};


export type QueryBackstageArtistsArgs = {
  input?: InputMaybe<ArtistsInput>;
};


export type QueryBackstageGenreArgs = {
  id: Scalars['String']['input'];
};


export type QueryBackstageGenresArgs = {
  input?: InputMaybe<GenresInput>;
};

export type UpdateArtistInput = {
  genres: Array<Scalars['String']['input']>;
  name: Scalars['String']['input'];
  verified: Scalars['Boolean']['input'];
};

export type UpdateGenreInput = {
  name: Scalars['String']['input'];
  slug: Scalars['String']['input'];
};

export type UploadToken = {
  __typename?: 'UploadToken';
  uploadToken: Scalars['String']['output'];
};

export type CreateArtistMutationVariables = Exact<{
  artist: CreateArtistInput;
}>;


export type CreateArtistMutation = { __typename?: 'Mutation', createArtist: { __typename?: 'BackstageArtist', id: string } };

export type GenerateArtistArtworkUploadTokenMutationVariables = Exact<{
  id: Scalars['String']['input'];
}>;


export type GenerateArtistArtworkUploadTokenMutation = { __typename?: 'Mutation', generateArtistArtworkUploadToken: { __typename?: 'UploadToken', uploadToken: string } };

export type GetBackstageArtistQueryVariables = Exact<{
  id: Scalars['String']['input'];
}>;


export type GetBackstageArtistQuery = { __typename?: 'Query', backstageArtist: { __typename?: 'BackstageArtist', id: string, name: string, verified: boolean, artwork?: { __typename?: 'Artwork', url: string } | null, genres?: Array<{ __typename?: 'BackstageGenre', id: string }> | null } };

export type UpdateArtistMutationVariables = Exact<{
  id: Scalars['String']['input'];
  artist: UpdateArtistInput;
}>;


export type UpdateArtistMutation = { __typename?: 'Mutation', updateArtist: { __typename?: 'BackstageArtist', id: string } };

export type GetBackstageArtistsQueryVariables = Exact<{ [key: string]: never; }>;


export type GetBackstageArtistsQuery = { __typename?: 'Query', backstageArtists: Array<{ __typename?: 'BackstageArtist', id: string, name: string, status: string, mediaStatus?: string | null, artwork?: { __typename?: 'Artwork', url: string } | null }> };

export type CreateGenreMutationVariables = Exact<{
  genre: CreateGenreInput;
}>;


export type CreateGenreMutation = { __typename?: 'Mutation', createGenre: { __typename?: 'BackstageGenre', id: string, name: string, slug: string } };

export type GetBackstageGenreQueryVariables = Exact<{
  id: Scalars['String']['input'];
}>;


export type GetBackstageGenreQuery = { __typename?: 'Query', backstageGenre: { __typename?: 'BackstageGenre', id: string, name: string, slug: string } };

export type UpdateGenreMutationVariables = Exact<{
  id: Scalars['String']['input'];
  genre: UpdateGenreInput;
}>;


export type UpdateGenreMutation = { __typename?: 'Mutation', updateGenre: { __typename?: 'BackstageGenre', id: string } };

export type GetBackstageGenresQueryVariables = Exact<{ [key: string]: never; }>;


export type GetBackstageGenresQuery = { __typename?: 'Query', backstageGenres: Array<{ __typename?: 'BackstageGenre', id: string, name: string, slug: string, status: string }> };

export type GetBackstageGenresByFilterQueryVariables = Exact<{
  input?: InputMaybe<GenresInput>;
}>;


export type GetBackstageGenresByFilterQuery = { __typename?: 'Query', backstageGenres: Array<{ __typename?: 'BackstageGenre', id: string, name: string }> };


export const CreateArtistDocument = gql`
    mutation CreateArtist($artist: CreateArtistInput!) {
  createArtist(artist: $artist) {
    id
  }
}
    ` as unknown as TypedDocumentNode<CreateArtistMutation, CreateArtistMutationVariables>;

@Injectable()
export class CreateArtistGql extends GraphqlMutation<CreateArtistMutation, CreateArtistMutationVariables> {
  override readonly document = CreateArtistDocument;
}
export const GenerateArtistArtworkUploadTokenDocument = gql`
    mutation GenerateArtistArtworkUploadToken($id: String!) {
  generateArtistArtworkUploadToken(id: $id) {
    uploadToken
  }
}
    ` as unknown as TypedDocumentNode<GenerateArtistArtworkUploadTokenMutation, GenerateArtistArtworkUploadTokenMutationVariables>;

@Injectable()
export class GenerateArtistArtworkUploadTokenGql extends GraphqlMutation<GenerateArtistArtworkUploadTokenMutation, GenerateArtistArtworkUploadTokenMutationVariables> {
  override readonly document = GenerateArtistArtworkUploadTokenDocument;
}
export const GetBackstageArtistDocument = gql`
    query GetBackstageArtist($id: String!) {
  backstageArtist(id: $id) {
    id
    name
    verified
    artwork {
      url
    }
    genres {
      id
    }
  }
}
    ` as unknown as TypedDocumentNode<GetBackstageArtistQuery, GetBackstageArtistQueryVariables>;

@Injectable()
export class GetBackstageArtistGql extends GraphqlQuery<GetBackstageArtistQuery, GetBackstageArtistQueryVariables> {
  override readonly document = GetBackstageArtistDocument;
}
export const UpdateArtistDocument = gql`
    mutation UpdateArtist($id: String!, $artist: UpdateArtistInput!) {
  updateArtist(id: $id, artist: $artist) {
    id
  }
}
    ` as unknown as TypedDocumentNode<UpdateArtistMutation, UpdateArtistMutationVariables>;

@Injectable()
export class UpdateArtistGql extends GraphqlMutation<UpdateArtistMutation, UpdateArtistMutationVariables> {
  override readonly document = UpdateArtistDocument;
}
export const GetBackstageArtistsDocument = gql`
    query GetBackstageArtists {
  backstageArtists {
    id
    name
    status
    mediaStatus
    artwork {
      url
    }
  }
}
    ` as unknown as TypedDocumentNode<GetBackstageArtistsQuery, GetBackstageArtistsQueryVariables>;

@Injectable()
export class GetBackstageArtistsGql extends GraphqlQuery<GetBackstageArtistsQuery, GetBackstageArtistsQueryVariables> {
  override readonly document = GetBackstageArtistsDocument;
}
export const CreateGenreDocument = gql`
    mutation CreateGenre($genre: CreateGenreInput!) {
  createGenre(genre: $genre) {
    id
    name
    slug
  }
}
    ` as unknown as TypedDocumentNode<CreateGenreMutation, CreateGenreMutationVariables>;

@Injectable()
export class CreateGenreGql extends GraphqlMutation<CreateGenreMutation, CreateGenreMutationVariables> {
  override readonly document = CreateGenreDocument;
}
export const GetBackstageGenreDocument = gql`
    query GetBackstageGenre($id: String!) {
  backstageGenre(id: $id) {
    id
    name
    slug
  }
}
    ` as unknown as TypedDocumentNode<GetBackstageGenreQuery, GetBackstageGenreQueryVariables>;

@Injectable()
export class GetBackstageGenreGql extends GraphqlQuery<GetBackstageGenreQuery, GetBackstageGenreQueryVariables> {
  override readonly document = GetBackstageGenreDocument;
}
export const UpdateGenreDocument = gql`
    mutation UpdateGenre($id: String!, $genre: UpdateGenreInput!) {
  updateGenre(id: $id, genre: $genre) {
    id
  }
}
    ` as unknown as TypedDocumentNode<UpdateGenreMutation, UpdateGenreMutationVariables>;

@Injectable()
export class UpdateGenreGql extends GraphqlMutation<UpdateGenreMutation, UpdateGenreMutationVariables> {
  override readonly document = UpdateGenreDocument;
}
export const GetBackstageGenresDocument = gql`
    query GetBackstageGenres {
  backstageGenres {
    id
    name
    slug
    status
  }
}
    ` as unknown as TypedDocumentNode<GetBackstageGenresQuery, GetBackstageGenresQueryVariables>;

@Injectable()
export class GetBackstageGenresGql extends GraphqlQuery<GetBackstageGenresQuery, GetBackstageGenresQueryVariables> {
  override readonly document = GetBackstageGenresDocument;
}
export const GetBackstageGenresByFilterDocument = gql`
    query GetBackstageGenresByFilter($input: GenresInput) {
  backstageGenres(input: $input) {
    id
    name
  }
}
    ` as unknown as TypedDocumentNode<GetBackstageGenresByFilterQuery, GetBackstageGenresByFilterQueryVariables>;

@Injectable()
export class GetBackstageGenresByFilterGql extends GraphqlQuery<GetBackstageGenresByFilterQuery, GetBackstageGenresByFilterQueryVariables> {
  override readonly document = GetBackstageGenresByFilterDocument;
}