import type { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
  overwrite: true,
  schema: '../../apps/server/schema.gql',
  documents: '../../apps/web/**/*.gql',
  generates: {
    // https://the-guild.dev/graphql/codegen/docs/getting-started/development-workflow
    '../../apps/web/src/app/shared/generated-types.ts': {
      plugins: [
        {
          add: {
            content: '/* eslint-disable -- generated by GraphQL Code Generator */\n',
            placement: 'prepend',
          },
        },
        'typescript',
        'typescript-operations',
        './dist/angular-urql-graphql/index.js',
      ],
      config: {
        operationsImportPath: '@/core/services/graphql-operations',
      },
      // Could add `addTypenameSelectionDocumentTransform` from '@graphql-codegen/client-preset' to add __typename to the query variables in case Graphcache is used
    },
  },
  watch: true,
}

export default config
