$schema: 'https://moonrepo.dev/schemas/tasks.json'

implicitDeps:
  - '^:build'

implicitInputs:
  - 'package.json'

fileGroups:
  app: []
  configs:
    - '*.{js,json,yml,yaml}'
    - 'eslint.config.mjs'
    - '.prettierignore'
    - '.prettierrc'
  sources:
    - 'src/**/*'
  unit-tests:
    - 'src/**/*.spec.*'
  contract-tests:
    - 'contract-tests/**/*'
    - '$workspaceRoot/contracts/*'
  integration-tests:
    - 'integration-tests/**/*'
  performance-tests:
    - 'performance-tests/**/*'

tasks:
  test-unit:
    command: 'vitest --config vitest.config.mts'
    inputs:
      - '@globs(sources)'
      - '@globs(unit-tests)'
      - 'vitest.config.*'
    outputs:
      - 'coverage'
      - 'reports/unit'

  test-contract:
    command: 'vitest --config vitest-contract.config.mts'
    local: true
    inputs:
      - '@group(sources)'
      - '@group(contract-tests)'
      - 'vitest-contract.config.*'
    outputs:
      - 'reports/contract'

  lint:
    command:
      - 'eslint'
      - '--fix'
    inputs:
      - '@group(sources)'
      - '@group(configs)'

  # sonar:
  #   command: 'sonar-scanner'
  #   local: true
  #   args:
  #     - 'Dsonar.token=${SONAR_TOKEN}'
  #   inputs:
  #     - '@group(sources)'
  #     - '@group(unit-tests)'
  #     - 'sonar-project.properties'
  #   deps:
  #     - 'test-unit'
