$schema: 'https://moonrepo.dev/schemas/tasks.json'

fileGroups:
  configs:
    - '*.{js,json,yml,yaml}'
    - 'eslint.config.mjs'
    - '.prettierignore'
    - '.prettierrc'
  sources:
    - 'src/**/*'

tasks:
  validate:
    command: 'tsc --noEmit'
    inputs:
      - '@group(sources)'
      - '@group(configs)'

  lint:
    command:
      - 'eslint'
      - '--fix'
    inputs:
      - '@group(sources)'
      - '@group(configs)'
