{
 "title": "Application Dashboard",
 "description": "request rate, error rate, duration",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RED Metrics: (r)equest rate, (e)rror rate, (d)uration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "RED",
   "type": "table",
   "description": "Some routes filtered out (http_route!~\".*/actuator.*\")",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(sum by (deployment_environment, service_name, http_method, http_route) (rate({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count|http_server_duration_milliseconds_count|http_server_duration_seconds_count|http_server_duration_count\", job=~\"$job\", instance=~\"$instance\"}[$__range]))[$__range:$__range]) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (deployment_environment, service_name, http_method, http_route) (rate({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count|http_server_duration_milliseconds_count|http_server_duration_seconds_count|http_server_duration_count\", job=~\"$job\", instance=~\"$instance\", http_response_status_code=~\"5..\"}[$__range:$__rate_interval]))\n/\nsum by (deployment_environment, service_name, http_method, http_route) (rate({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count|http_server_duration_milliseconds_count|http_server_duration_seconds_count|http_server_duration_count\", job=~\"$job\", instance=~\"$instance\"}[$__range:$__rate_interval]))) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (deployment_environment, service_name, http_method, http_route, le) (rate({__name__=~\"http_server_request_duration_seconds_bucket|http_server_request_duration_bucket|http_server_duration_milliseconds_bucket|http_server_duration_seconds_bucket|http_server_duration_bucket\", job=~\"$job\", instance=~\"$instance\"}[$__range:$__rate_interval]))) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (deployment_environment, service_name, http_method, http_route) (increase({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count|http_server_duration_milliseconds_count|http_server_duration_seconds_count|http_server_duration_count\", job=~\"$job\", instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count|http_server_duration_milliseconds_count|http_server_duration_seconds_count|http_server_duration_count\", job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count|http_server_duration_milliseconds_count|http_server_duration_seconds_count|http_server_duration_count\", job=~\"$job\", instance=~\"$instance\", http_response_status_code=~\"5..\"}[5m])) / sum(rate({__name__=~\"http_server_request_duration_seconds_count|http_server_request_duration_count|http_server_duration_milliseconds_count|http_server_duration_seconds_count|http_server_duration_count\", job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Duration percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate({__name__=~\"http_server_request_duration_seconds_bucket|http_server_request_duration_bucket|http_server_duration_milliseconds_bucket|http_server_duration_seconds_bucket|http_server_duration_bucket\", job=~\"$job\", instance=~\"$instance\"}[5m])))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate({__name__=~\"http_server_request_duration_seconds_bucket|http_server_request_duration_bucket|http_server_duration_milliseconds_bucket|http_server_duration_seconds_bucket|http_server_duration_bucket\", job=~\"$job\", instance=~\"$instance\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (le) (rate({__name__=~\"http_server_request_duration_seconds_bucket|http_server_request_duration_bucket|http_server_duration_milliseconds_bucket|http_server_duration_seconds_bucket|http_server_duration_bucket\", job=~\"$job\", instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Duration histogram (s)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate({__name__=~\"http_server_request_duration_seconds_bucket|http_server_request_duration_bucket|http_server_duration_milliseconds_bucket|http_server_duration_seconds_bucket|http_server_duration_bucket\", job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Application map",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Mesh",
     "type": "nodeGraph",
     "gridPos": { "h": 15, "w": 11, "x": 0, "y": 36 },
     "targets": [
      { "limit": 20, "serviceMapQuery": "{}", "tableType": "traces" }
     ]
    }
   ]
  }
 ]
}