name: 'Pipeline'

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  statuses: write
  checks: write

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  ci:
    name: 'CI'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: moonrepo/setup-toolchain@v0
      - run: 'moon ci --color'

      - name: 'Publish run results'
        uses: moonrepo/run-report-action@v1
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
